/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wedrive_android_welink_jni_FFmpegUtils_OnDecodeListener */

#ifndef _Included_com_wedrive_android_welink_jni_FFmpegUtils_OnDecodeListener
#define _Included_com_wedrive_android_welink_jni_FFmpegUtils_OnDecodeListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
