/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wedrive_android_welink_jni_FFmpegUtils */

#ifndef _Included_com_wedrive_android_welink_jni_FFmpegUtils
#define _Included_com_wedrive_android_welink_jni_FFmpegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wedrive_android_welink_jni_FFmpegUtils
 * Method:    decodeFile4Jni
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wedrive_android_welink_jni_FFmpegUtils_decodeFile4Jni
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_wedrive_android_welink_jni_FFmpegUtils
 * Method:    initdecode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wedrive_android_welink_jni_FFmpegUtils_initdecode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wedrive_android_welink_jni_FFmpegUtils
 * Method:    destorydecode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wedrive_android_welink_jni_FFmpegUtils_destorydecode
  (JNIEnv *, jobject);

/*
 * Class:     com_wedrive_android_welink_jni_FFmpegUtils
 * Method:    decodeStream
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wedrive_android_welink_jni_FFmpegUtils_decodeStream
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
